<?php
/**
 * This widget setup and comments were referenced from Lecture 10 CCT460 Building a WordPress Widget
 **/
// Creates the Subscriber Gallery Widget
class SubscriberGalleryWidget extends WP_Widget
{

    // Initializes the Widget
    public function __construct()
    {
        $widget_ops = array(
            'classname' => 'widget_archive',
            'description' => __('A community creations of recent posts on Cuisine a la toile site&#8217;s.', 'cuisine-a-la-toile')
        );
        // Adds a class to the widget
        // Provides a description on the Widget page explaining the widget's purpose
        parent::__construct('community_archives', __('Cuisine Widget', 'cuisine-a-la-toile'), $widget_ops);
    }


    // Determines what will appear on the site
    public function widget($args, $instance)
    {
        $order = !empty($instance['cuisine-widget-order']) ? 'ASC' : 'DESC';
        //sets a variable for the 'cuisine-widget-order' option
        $number = !empty($instance['cuisine-widget-number']) ? $instance['cuisine-widget-number'] : 3;
        // sets a variable for the 'cuisine-widget-number' option
        $title = apply_filters('widget_title', empty($instance['title']) ? __('Community Creations', 'cuisine-a-la-toile') : $instance['title'], $instance, $this->id_base);
        // Determines whether a title is provided by the user. If this is not provided, the default title is displayed

        echo $args['before_widget']; // Appears once the sidebar is registered.

        echo $args['before_title'] . $title . $args['after_title'];

        $button_id = "widget-cuisine-see-all-{$this->id_base}-{$this->number}";

        $cuisine_creation_options = array(
            'query' => array(
                'posts_per_page' => $number,
                'order' =>  $order
            )
        );
        ?>
        <label class="screen-reader-text" for="<?= esc_attr($button_id) ?>"><?= $title ?></label>
        <?= cuisine_render_creations($cuisine_creation_options); ?>
        <button id="<?= esc_attr($button_id) ?>" onclick="document.location.href='<?=get_post_type_archive_link( 'cuisine_creation' );?>';">See All Creations</button>

        <?php echo $args['after_widget']; // Appears once the sidebar is registered.
    }

    // Form Set up. Allows users to customize the widget in the widget admin page.
    // Backend Form
    public function form($instance)
    {
        $instance = wp_parse_args((array)$instance, array('title' => '',  'cuisine-widget-number' => 3, 'cuisine-widget-order' => ''));
        $title = strip_tags($instance['title']);
        $number = $instance['cuisine-widget-number'];
        $is_ascending =  $instance['cuisine-widget-order'] ? 'checked="checked"' : '';
        ?>
        <div class="cuisine-widget-options">
            <br/>
            <label
                for="<?php echo $this->get_field_id('title'); ?>"><?php _e('Title:', 'cuisine-a-la-toile'); ?></label>
            <input class="widefat" id="<?php echo $this->get_field_id('title'); ?>"
                   name="<?php echo $this->get_field_name('title'); ?>" type="text"
                   value="<?php echo esc_attr($title); ?>"/>
            <br/>
            <br/>

            <label
                for="<?= $this->get_field_id('cuisine-widget-order'); ?>">
                <?=__('Number of Creations Shown:', 'cuisine-a-la-toile'); ?>
            </label>
            <select id="<?=esc_attr($this->get_field_id('cuisine-widget-number'))?>"
                    name="<?=esc_attr($this->get_field_name('cuisine-widget-number'))?>">

                <?php
                for($i=1; $i<=10; $i++){
                    $is_selected = (($i==$number)?'selected="selected"':'');
                    ?>
                     <option value="<?=$i?>" <?=$is_selected?>><?=$i?></option>
                    <?php
                }
                ?>
            </select>
         <br/>
            <br/>
            <input class="checkbox" type="checkbox" <?=$is_ascending?>
                   id="<?= $this->get_field_id('cuisine-widget-order'); ?>"
                   name="<?= $this->get_field_name('cuisine-widget-order'); ?>"/>
            <label
                for="<?= $this->get_field_id('cuisine-widget-order'); ?>"><?php _e('Display Oldest Creations First', 'cuisine-a-la-toile'); ?></label>
            <br/>
            <br/>
            <br/>
            <br/>
        </div>

    <?php }

    // Saves and submits the content generated by the user.

    public function update($new_instance, $old_instance)
    {
        $instance = $old_instance;
        $new_instance = wp_parse_args((array)$new_instance, array('title' => '', 'cuisine-widget-order' => 0, 'cuisine-widget-number' => 3));
        $instance['title'] = strip_tags($new_instance['title']);
        $instance['cuisine-widget-order'] = $new_instance['cuisine-widget-order'] ? 1 : 0;
        $instance['cuisine-widget-number'] = $new_instance['cuisine-widget-number'];
        return $instance;
    }
}

// Informs WordPress that the widget has been created and should be listed along with the rest of the available widgets.
function cuisine_register_community_creations_widget()
{
    register_widget('SubscriberGalleryWidget');
}

add_action('widgets_init', 'cuisine_register_community_creations_widget');
?>
